cleanup

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -99,43 +99,43 @@ jobs:
         name: build-info-${{ matrix.project }}
         path: build-info.txt
 
-  finalise:
-    name: Update ArgoCD
-    runs-on: ubuntu-latest
-    needs: build
-    if: always() # This ensures the job runs even a build fails
-    steps:
-      - name: Check Out Repository
-        uses: actions/checkout@v3
+  # finalise:
+  #   name: Update ArgoCD
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   if: always() # This ensures the job runs even a build fails
+  #   steps:
+  #     - name: Check Out Repository
+  #       uses: actions/checkout@v3
 
-      - name: Download all artifacts
-        uses: actions/download-artifact@v3
+  #     - name: Download all artifacts
+  #       uses: actions/download-artifact@v3
 
-      - name: Combine and Process Build Info
-        run: |
-          for dir in build-info-*; do
-            if [ -d "$dir" ]; then
-              cat "$dir/build-info.txt" >> combined-build-info.txt
-            fi
-          done
+  #     - name: Combine and Process Build Info
+  #       run: |
+  #         for dir in build-info-*; do
+  #           if [ -d "$dir" ]; then
+  #             cat "$dir/build-info.txt" >> combined-build-info.txt
+  #           fi
+  #         done
 
-      - name: Update ArgoCD Manifests
-        run: |
-          while IFS='=' read -r project image_tag; do
-            deployment_file="apps/${project}/deployment.yml"
-            if [ -f "$deployment_file" ]; then
-              sed -i "s|image: .*|image: ${image_tag}|" "$deployment_file"
-            else
-              echo "Deployment file for ${project} not found"
-            fi
-          done < combined-build-info.txt
+  #     - name: Update ArgoCD Manifests
+  #       run: |
+  #         while IFS='=' read -r project image_tag; do
+  #           deployment_file="apps/${project}/deployment.yml"
+  #           if [ -f "$deployment_file" ]; then
+  #             sed -i "s|image: .*|image: ${image_tag}|" "$deployment_file"
+  #           else
+  #             echo "Deployment file for ${project} not found"
+  #           fi
+  #         done < combined-build-info.txt
 
-      - name: Commit and Push Changes
-        run: |
-          git config --local user.name "GitHub Action"
-          git config --local user.email "action@github.com"
-          git add apps/
-          git diff --staged --quiet || {
-            git commit -m "Update image tags for applications [skip ci]"
-            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
-          }
+  #     - name: Commit and Push Changes
+  #       run: |
+  #         git config --local user.name "GitHub Action"
+  #         git config --local user.email "action@github.com"
+  #         git add apps/
+  #         git diff --staged --quiet || {
+  #           git commit -m "Update image tags for applications [skip ci]"
+  #           git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
+  #         }
